### ISSUE TITLE
Prisma many connection

### ISSUE THREAD

**Issue by universenl** [Undefined-Developers/Discord.js-v14-TS-handler#1]
Got a question about the prisma integration.

Using this with mongodb and it seems that its not dropping any conenctions after use. Using pooling but after a couple of hours reaching max connection of the mongodb atlas server.

Do you have any idea about how and why ?

**Comment by Rocky-pup** [comment]
I have no idea because I have no experience with mongodb. With postgresql it works fine, so I assume it's mongodb issue. I suggest you to use psql cause it's alot faster and can handle more requests/second, at least on the time I was testing. 
I'll investigate it, but I can't give you ETA because I have some irl stuff to do.

**Comment by universenl** [comment]
Sounds good!

**Comment by Rocky-pup** [comment]
So.. I've done some testing, and sometimes for no reason prisma makes second connection to postgresql (yes, it's a little unrelated, but I need to point it out). I found solution, which is very simple. After that I started testing mongodb. I've created Atlas account and cluster. It successfully connected and worked fine, connections usually stay around 5 after few reboots and few ping commands, so I guess it's not related to my code. I'm still not sure how mongodb works)

**Comment by universenl** [comment]
![image](https://github.com/user-attachments/assets/47a45d70-bbc5-4256-a3d1-5d0dadb81518)

This are the connection on mongodb on my end.

If i spam commands it goes up insane fast and stays there for like a very long time untill it drops.

**Comment by universenl** [comment]
Still got the idea that every command creates a new connection tho.

**Comment by Rocky-pup** [comment]
If you're spamming commands it isn't possible to increase connections because every db request gets cached.
Ping command on the other hand directly requests database to respond on ping with no cache. Check my latest commits and ensure to uncomment ping for mongodb in structures/Database.ts and comment regular one. I ask this because I have no idea what command you running and what ping method is being used because what I had initially isn't compatible with mongodb

**Comment by Rocky-pup** [comment]
Also, are you sure it's problem with my handler? Do you have some other applications that can be connected alongside?

**Comment by universenl** [comment]
Sure there is only 1 application connecting to that mongodb instance. Have updated everything that you changed in the latest commits, still having high connection count.

**Comment by universenl** [comment]
Got it fixed, found an extra of prisma client somewhere.
